server:
  port: 4000
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
      probes:
         enabled: true
      group:
        liveness:
          include: "livenessState,ping"
        readiness:
          include: "readinessState,db,diskSpace,ping"
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "info, health, metrics"

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dev.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/test/"
  application:
    name: Dev Test

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:dev-db.sqlite
  
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
